### ISSUE TITLE
Add a README and populate the repo

### ISSUE THREAD

**Issue by nigelmegitt** [w3c/ttml1-tests#1]
This repo currently doesn't include any TTML1 tests!

We should:

* Add detail to the README to explain that this is a non-normative suite of tests for general use when testing implementations against TTML1, and that it is _not_ the test suite used for CR exit criteria assessment (and point to where that is, i.e. https://github.com/w3c/ttml1/tree/master/testsuite)
* Populate the repo with the TTML1 tests that we have, from https://github.com/w3c/ttml1/tree/master/testsuite

**Comment by nigelmegitt** [comment]
Also consider referencing or bringing in any additional tests from https://github.com/w3c/imsc-tests if they test functionality not yet tested here.

**Comment by skynavga** [comment]
@nigelmegitt I've just looked at this, and I believe it was my intent to populate this repo using the much larger set of tests used to test TTML1 support in TTV [1] and TTPE [2], i.e., following the same path I took when I populated the ttml2-tests repo; for the legacy testsuite files, my intent was to additionally ensure that the were covered by the tests coming out of of TTV and TTPE;

[1] https://github.com/skynav/ttt/tree/master/ttt-ttv/src/test/resources/com/skynav/ttv/ttml1
[2] https://github.com/skynav/ttt/tree/master/ttt-ttpe/src/test/resources/com/skynav/ttpe/ttml1

Would you be open to me taking the initiative to do this? I believe we could readily integrate the new imsc11 based tests in this process as well.

**Comment by nigelmegitt** [comment]
[oops, I thought I'd posted this on Friday but it doesn't look like I hit the green button]

Hi @skynavga absolutely, please go ahead. It looks like that would be one source of tests, in addition to the tests in the ttml1 repo and maybe the imsc repo. I suggest we don't give particular prominence to any particular source of tests.

**Comment by skynavga** [comment]
Merged from #3.
